services:
  - type: web
    name: n8n-invoice-automation
    env: docker
    plan: free
    autoDeploy: true

    dockerfilePath: ./Dockerfile

    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        sync: false

      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

      - key: OPENROUTER_API_KEY
        sync: false

      - key: LLAMAPARSE_API_KEY
        sync: false
